# Generated by Django 3.2.9 on 2022-04-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdriven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hourlyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
