# Generated by Django 3.2.9 on 2022-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdriven', '0002_auto_20220422_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='hourlyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
    ]
