# Generated by Django 3.2.9 on 2022-04-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdriven', '0003_auto_20220423_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyperformance',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='hourlyperformance',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12),
        ),
    ]
